name: golangci-lint
on:
  push:
    branches:
      - main
      - v*
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.2
          only-new-issues: false
          args: --timeout=5m --fast
