name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write  # Required for OIDC JWT authentication

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    outputs:
      macos_sign_p12: ${{ steps.secrets.outputs.MACOS_SIGN_P12 }}
      macos_sign_password: ${{ steps.secrets.outputs.MACOS_SIGN_PASSWORD }}
      macos_sign_identity: ${{ steps.secrets.outputs.MACOS_SIGN_IDENTITY }}
      macos_notary_issuer_id: ${{ steps.secrets.outputs.MACOS_NOTARY_ISSUER_ID }}
      macos_notary_key_id: ${{ steps.secrets.outputs.MACOS_NOTARY_KEY_ID }}
      macos_notary_key: ${{ steps.secrets.outputs.MACOS_NOTARY_KEY }}
      macos_installer_p12: ${{ steps.secrets.outputs.MACOS_INSTALLER_P12 }}
      macos_installer_password: ${{ steps.secrets.outputs.MACOS_INSTALLER_PASSWORD }}
      macos_installer_identity: ${{ steps.secrets.outputs.MACOS_INSTALLER_IDENTITY }}
      keychain_password: ${{ steps.secrets.outputs.KEYCHAIN_PASSWORD }}
      chocolatey_api_key: ${{ steps.secrets.outputs.CHOCOLATEY_API_KEY }}
      committer_token: ${{ steps.secrets.outputs.COMMITTER_TOKEN }}
    steps:
    - name: Fetch secrets from CyberArk Conjur
      id: secrets
      uses: cyberark/conjur-action@v2.0.12
      with:
        url: https://pineapple.secretsmgr.cyberark.cloud/api
        authn_id: inf-github
        account: conjur
        secrets: |
          data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_SIGN_P12|MACOS_SIGN_P12;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_SIGN_PASSWORD|MACOS_SIGN_PASSWORD;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_SIGN_IDENTITY|MACOS_SIGN_IDENTITY;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_NOTARY_ISSUER_ID|MACOS_NOTARY_ISSUER_ID;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_NOTARY_KEY_ID|MACOS_NOTARY_KEY_ID;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_NOTARY_KEY|MACOS_NOTARY_KEY;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_INSTALLER_P12|MACOS_INSTALLER_P12;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_INSTALLER_PASSWORD|MACOS_INSTALLER_PASSWORD;data/infamousdevops/ci/github/infamousjoeg/conceal/MACOS_INSTALLER_IDENTITY|MACOS_INSTALLER_IDENTITY;data/infamousdevops/ci/github/infamousjoeg/conceal/KEYCHAIN_PASSWORD|KEYCHAIN_PASSWORD;data/infamousdevops/ci/github/infamousjoeg/conceal/CHOCOLATEY_API_KEY|CHOCOLATEY_API_KEY;data/infamousdevops/ci/github/infamousjoeg/conceal/COMMITTER_TOKEN|COMMITTER_TOKEN

  release:
    needs: fetch-secrets
    runs-on: macos-latest  # Changed to macOS for code signing and notarization
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Generate changelog
      run: |
        # Generate changelog since last tag without committing (GoReleaser handles changelog)
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -n "$PREV_TAG" ]; then
          echo "## Changes since $PREV_TAG" > CHANGELOG.md
          git log --oneline $PREV_TAG..HEAD >> CHANGELOG.md
        else
          echo "## Initial Release" > CHANGELOG.md
          git log --oneline >> CHANGELOG.md
        fi
        echo "Generated changelog for reference"

    - name: Import Code-Signing Certificates
      if: ${{ needs.fetch-secrets.outputs.macos_sign_p12 != '' }}
      run: |
        # Create variables for certificate handling
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        
        # Import certificate and provisioning profile from secrets
        echo -n "${{ needs.fetch-secrets.outputs.macos_sign_p12 }}" | base64 --decode -o $CERTIFICATE_PATH
        
        # Create temporary keychain
        security create-keychain -p "${{ needs.fetch-secrets.outputs.keychain_password }}" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "${{ needs.fetch-secrets.outputs.keychain_password }}" $KEYCHAIN_PATH
        
        # Import certificate to keychain
        security import $CERTIFICATE_PATH -P "${{ needs.fetch-secrets.outputs.macos_sign_password }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -s -k "${{ needs.fetch-secrets.outputs.keychain_password }}" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: ${{ github.event_name == 'workflow_dispatch' && 'build --snapshot --clean' || 'release --clean --skip=validate' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Apple Developer Code Signing (from Conjur)
        MACOS_SIGN_P12: ${{ needs.fetch-secrets.outputs.macos_sign_p12 }}
        MACOS_SIGN_PASSWORD: ${{ needs.fetch-secrets.outputs.macos_sign_password }}
        MACOS_SIGN_IDENTITY: ${{ needs.fetch-secrets.outputs.macos_sign_identity }}
        # Apple Developer Notarization (from Conjur)  
        MACOS_NOTARY_ISSUER_ID: ${{ needs.fetch-secrets.outputs.macos_notary_issuer_id }}
        MACOS_NOTARY_KEY_ID: ${{ needs.fetch-secrets.outputs.macos_notary_key_id }}
        MACOS_NOTARY_KEY: ${{ needs.fetch-secrets.outputs.macos_notary_key }}
        # Apple Developer ID Installer (from Conjur)
        MACOS_INSTALLER_P12: ${{ needs.fetch-secrets.outputs.macos_installer_p12 }}
        MACOS_INSTALLER_PASSWORD: ${{ needs.fetch-secrets.outputs.macos_installer_password }}
        MACOS_INSTALLER_IDENTITY: ${{ needs.fetch-secrets.outputs.macos_installer_identity }}
        # Chocolatey Package Management (from Conjur)
        CHOCOLATEY_API_KEY: ${{ needs.fetch-secrets.outputs.chocolatey_api_key }}

    - name: Clean up keychain
      if: ${{ always() }}
      run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db || true

  homebrew-update:
    needs: [fetch-secrets, release]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Update Homebrew formula
      uses: mislav/bump-homebrew-formula-action@v3
      with:
        formula-name: conceal
        homebrew-tap: infamousjoeg/homebrew-tap
        base-branch: master
      env:
        COMMITTER_TOKEN: ${{ needs.fetch-secrets.outputs.committer_token || secrets.COMMITTER_TOKEN }}
